###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: docker-mysql
      working_dir: /application
      restart: always
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      ports:
        - "8082:3306"

    composer:
      container_name: docker-composer
      image: composer
      command: install -n
      volumes:
        - ./sample-symfony:/app

    elasticsearch:
      image: elasticsearch:2.4-alpine
      container_name: docker-elasticsearch
      ports:
        - 9300:9300
        - 9200:9200

    php:
      build: ./phpdocker/php-fpm
      container_name: docker-php
      working_dir: /application
      volumes:
        - ./sample-symfony:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    webserver:
      image: nginx:alpine
      container_name: docker-webserver
      working_dir: /application
      volumes:
        - ./sample-symfony:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "5001:80"
      depends_on:
        - php
        - composer
        - mysql
        - elasticsearch